"""Extract the YC1021 Bluetooth init table from Leo's V2.87 application image into C source.

In the V2.87 APP1 image (linked at 0x08008000) the table sits at 0x08018C94:
    u16 total_length (little-endian), then records [n][01 op_lo op_hi len payload...]
    op 0xFC03 x34  - patch/program upload (~8 KB)
    op 0xFC10 x70  - memory writes: <count> <addr_lo> <addr_hi> <data> (names, SPP record, GATT, RF)
    op 0xFC04 x1   - final command (start)
Output: src/bt_init_table.c
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "..", "From Leo", "05_Firmware_Binaries", "X-Box_V2.87_APP1.bin")
OUT = os.path.join(HERE, "..", "src", "bt_init_table.c")
BASE = 0x08008000
TABLE = 0x08018C94


def main():
    b = open(SRC, "rb").read()
    start = TABLE - BASE
    length = b[start] | b[start + 1] << 8
    i, recs = start + 2, []
    while i < start + 2 + length:
        n = b[i]
        r = b[i + 1:i + 1 + n]
        if n < 4 or r[0] != 0x01 or r[2] != 0xFC or r[3] != n - 4:
            break
        recs.append(bytes([n]) + r)
        i += 1 + n
    data = b"".join(recs)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by tools/extract_bt_table.py from X-Box_V2.87_APP1.bin @0x%08X - do not edit */\n" % TABLE)
        f.write("#include <stdint.h>\n\n")
        f.write("/* %d records: [n][HCI command, n bytes] ... */\n" % len(recs))
        f.write("const uint16_t bt_init_table_count = %d;\n" % len(recs))
        f.write("const uint16_t bt_init_table_size = %d;\n" % len(data))
        f.write("const uint8_t bt_init_table[%d] = {\n" % len(data))
        for k in range(0, len(data), 16):
            f.write("    " + ", ".join("0x%02X" % x for x in data[k:k + 16]) + ",\n")
        f.write("};\n")
    print("records %d, bytes %d -> %s" % (len(recs), len(data), os.path.normpath(OUT)))


if __name__ == "__main__":
    main()
